---
- hosts: all
  become: true

  tasks:
    - name: Stop Container
      shell: docker stop minical

    - name: Remove Container
      shell: docker rm -f minical

    - name: Delete Image
      shell: docker image rm -f keiserdocker/minicalc:latest

    - name: Run the new image
      shell: docker run -d -p 6969:6969 --name minical keiserdocker/minicalc:latest -it