---
- hosts: all
  become: true

  tasks:
    - name: Stop Container
      shell: docker stop calculator

    - name: Remove Container
      shell: docker rm -f calculator

    - name: Delete Image
      shell: docker image rm -f keiserdocker/calculator-spemini:latest

    - name: Run the new image
      shell: docker run -d -p 80:80 --name calculator keiserdocker/calculator-spemini:latest